### ISSUE TITLE
Pastamancer Automated Ascension wasting turns

### ISSUE THREAD

**Issue by metool** [houeland/kolproxy#292]
I tried to automate a Softcores Standard Pastamancer run, and it looks like it spent over 200 turns trying to complete the Hidden Apartment Building. When I noticed it was stuck there, I manually adventured and got a warning that the Vampieroghi may remove negative effects after combat. I'm guessing that the Vampieroghi was removing the Once Cursed effect, causing it to keep burning turns trying to get Thrice Cursed.

**Comment by houeland** [comment]
I think this was supposed to be fixed earlier, but I guess only for manual automation. I'll fix it.

**Comment by Mushroomheadbangers** [comment]
I had this same issue come up on two different characters as well.
