### ISSUE TITLE
have_skill and cast_skill do not work with Jalapeño Saucesphere

### ISSUE THREAD

**Issue by soolar** [houeland/kolproxy#295]
Presumably they won't work with any other skills with characters outside of basic ASCII either.

**Comment by soolar** [comment]
Probably the best workaround would be to enable some way of checking if you have a skill by id number, rather than setting out to enable UTF-8 in lua or something like that. Unless there's already a way to do that, but I've looked, and didn't find anything like that.

**Comment by houeland** [comment]
The name of the skill is "Jalape&ntilde;o Saucesphere". Works fine.

(KoL *does* have unescaped non-ASCII in monster names, which is more of a bug than anything else, but annoying inconsistency.)

**Comment by soolar** [comment]
It is not working for me on windows in version 3.43. have_skill("Jalapeño Saucesphere") returns false, and I definitely know Jalapeño Saucesphere.

**Comment by houeland** [comment]
Github is interfering with the formatting. Do you mean that you write h a v e _ s k i l l ( " J a l a p e & n t i l d e ; o   S a u c e s p h e r e " ) and it doesn't work?

**Comment by soolar** [comment]
Oh, okay, I see the edit to your original comment now. That fixed it, thanks a ton!
