### ISSUE TITLE
learn knob password is the only thing kolproxy has adventured for in over 100 turns

### ISSUE THREAD

**Issue by Lod3r** [houeland/kolproxy#305]
Knob Goblin Elite Uniform equipped and its clearly trying to get the one time adventure to get the lab key. Yet I already have it. I tried buying everything in the dispensary to counteract it but its still continuing to adventure for the key. Not sure how to fix it.

**Comment by houeland** [comment]
Server store change broke the script, fixed in 3.44.

**Comment by Lod3r** [comment]
Thank you thank you thank you. I wasn't sure if this had been covered but it was making me loco. Thanks for your hard work.
