### ISSUE TITLE
KOL now uses https, which breaks KolProxy

### ISSUE THREAD

**Issue by ryanwilliamson** [houeland/kolproxy#378]
KOL has changed it's protocol to use https instead of http.  KolProxy is unable to connect currently.

**Comment by Mushroomheadbangers** [comment]
I was so sad when I tried to use kolproxy yesterday and it was broken. I felt so relieved when I saw you already had an issue open for it. I just needed to vent...thanks for all your hard work. I wish I could contribute.

**Comment by awaj2006** [comment]
I'm also having this issue and would like to hear when this issue gets resolved.
